from random import randint
from time import sleep



def diversos():
    diversos = [
    (2, 'Ácido'),
    (4, 'Água benta'),
    (5, 'Alaúde élfico'),
    (6, 'Algemas'),
    (8, 'Baga-de-fogo'),
    (23, 'Bálsamo restaurador'),
    (24, 'Bandana'),
    (25, 'Bandoleira de poções'),
    (30, 'Bomba'),
    (31, 'Botas reforçadas'),
    (32, 'Camisa bufante'),
    (33, 'Capa esvoaçante'),
    (34, 'Capa pesada'),
    (35, 'Casaco longo'),
    (36, 'Chapéu arcano'),
    (38, 'Coleção de livros'),
    (40, 'Cosmético'),
    (42, 'Dente-de-dragão'),
    (43, 'Enfeite de elmo'),
    (44, 'Elixir do amor'),
    (46, 'Equipamento de viagem'),
    (56, 'Essência de mana'),
    (57, 'Estojo de disfarces'),
    (58, 'Farrapos de ermitão'),
    (59, 'Flauta mística'),
    (66, 'Fogo alquímico'),
    (67, 'Gorro de ervas'),
    (69, 'Líquen lilás'),
    (70, 'Luneta'),
    (73, 'Maleta de medicamentos'),
    (74, 'Manopla'),
    (75, 'Manto eclesiástico'),
    (78, 'Mochila de aventureiro'),
    (80, 'Musgo púrpura'),
    (83, 'Organizador de pergaminhos'),
    (85, 'Pó de cristal'),
    (87, 'Pó de giz'),
    (88, 'Pó do desaparecimento'),
    (89, 'Robe místico'),
    (91, 'Saco de sal'),
    (92, 'Sapatos de camurça'),
    (94, 'Seixo de âmbar'),
    (95, 'Sela'),
    (96, 'Tabardo'),
    (97, 'Traje da corte'),
    (99, 'Terra de cemitério'),
    (100, 'Veste de seda')
    ]

def armas():
    armas = [
    (3, 'Adaga'),
    (5, 'Alabarda'),
    (7, 'Alfange'),
    (10, 'Arco curto'),
    (13, 'Arco longo'),
    (15, 'Azagaia'),
    (16, 'Balas (20)'),
    (18, 'Besta leve'),
    (20, 'Besta pesada'),
    (23, 'Bordão'),
    (24, 'Chicote'),
    (27, 'Cimitarra'),
    (30, 'Clava'),
    (31, 'Corrente de espinhos'),
    (33, 'Espada bastarda'),
    (38, 'Espada curta'),
    (43, 'Espada longa'),
    (46, 'Flechas (20)'),
    (49, 'Florete'),
    (51, 'Foice'),
    (53, 'Funda'),
    (55, 'Gadanho'),
    (56, 'Katana'),
    (59, 'Lança'),
    (60, 'Lança montada'),
    (63, 'Maça'),
    (66, 'Machadinha'),
    (67, 'Machado anão'),
    (70, 'Machado de batalha'),
    (73, 'Machado de guerra'),
    (74, 'Machado táurico'),
    (76, 'Mangual'),
    (77, 'Marreta'),
    (80, 'Martelo de guerra'),
    (83, 'Montante'),
    (84, 'Mosquete'),
    (85, 'Pedras (20)'),
    (88, 'Picareta'),
    (90, 'Pique'),
    (92, 'Pistola'),
    (93, 'Rede'),
    (96, 'Tacape'),
    (98, 'Tridente'),
    (100, 'Virotes (20)')
]

def armaduras():
    armaduras = [(5, 'Couro'),
    (10, 'Brunea'),
    (25, 'Completa'),
    (30, 'Cota de malha'),
    (45, 'Couraça'),
    (55, 'Couro batido'),
    (65, 'Escudo leve'),
    (80, 'Escudo pesado'),
    (85, 'Gibão de peles'),
    (90, 'Loriga segmentada'),
    (100, 'Meia armadura')
]

def esotéricos():
    esotéricos = [
    (10, 'Bolsa de Pó'),
    (25, 'Cajado Arcano'),
    (35, 'Cetro Elemental'),
    (42, 'Costela de Lich'),
    (50, 'Dedo de Ente'),
    (55, 'Luva de Ferro'),
    (65, 'Medalhão de Prata'),
    (75, 'Orbe Cristalina'),
    (85, 'Tomo Hermético'),
    (100, 'Varinha Arcana')
]
